CREATE DATABASE biblioteca_integrador;

USE biblioteca_integrador;

CREATE TABLE tb_livros (
    ID_LIVRO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(30) NOT NULL,
    AUTOR VARCHAR(30)NOT NULL,
    GENERO VARCHAR(20),
    EDITORA VARCHAR(50)NOT NULL,
    ISBN VARCHAR(17) NOT NULL,
    ANO_PUBLICACAO DATE NOT NULL,
    NUMERO_PAGINAS INT NOT NULL
);
SELECT * FROM tb_livros;